### ISSUE TITLE
The choice of a phylogenetic tree for the analysis

### ISSUE THREAD

**Issue by mavino** [PoonLab/comet-prot#12]
Re-reading the paper I came across this sentence:
"To run this analysis, you need to have a codon sequence alignment and a phylogenetic tree relating these sequences" at line 173 
and then at line 189 "A phylogenetic tree can be reconstructed from the sequence alignment using any standard maximum likelihood program such as RAxML \cite{Stamatakis:2014} (\url{https://github.com/stamatak/standard-RAxML}) or PhyML \cite{Guindon:2010}" .
It looks to me here that we are granting that a phylogenetic tree is always a maximum likelihood phylogenetic tree, while there are other phylogenetic trees that can be made (MP, for example). Shall we say a word here that we do prefer maximum likelihood phylogenetic trees for certain reasons?

**Comment by ArtPoon** [comment]
I don't think so --- let's just mention that we prefer ML but other methods are ok.

**Comment by ArtPoon** [comment]
Fixed in footnote
