### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/comet-prot#5]
There are a bunch of extra data files and scripts that we didn't end up using for the book chapter.
We also need to write a README.md

**Comment by mavino** [comment]
I will eliminate the files that have not been used for the book chapter
I can start writing a README.md.
I'll see some of your past ones, because I've never written one.
Do we need to complete a README file before submission?

**Comment by mavino** [comment]
Done with deleting files and scripts that are not cited in the book chapter

**Comment by ArtPoon** [comment]
Yeah I already did some clean up last night

**Comment by ArtPoon** [comment]
Re: README file, not really necessary but it's helpful if anyone actually accesses this repo and wants to understand what the files are for.

**Comment by mavino** [comment]
Yeah I agree, I recognize the importance of having a README file and I can make it...I was just wondering if I should do it before submitting the paper.
Any luck with the editor email you sent for an extended time or we are going to submit the paper by tomorrow anyway?

**Comment by ArtPoon** [comment]
Nope.  (By the way, this repo is public now :-) )

**Comment by mavino** [comment]
The README file is done.
