### ISSUE TITLE
Formatting requests

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/comet-prot#7]
* [x] key words
* [x] running head
* [x] double spacing
* [x] references numbered in order of appearance
* [x] separate all subheadings from associated text (line break)
* [x] figures in separate files from main text
* [x] notes is section 4, do not number acknowledgements section

**Comment by mavino** [comment]
am I wrong or since you used Springer LaTeX template the reference are finally numbered in order of appearance?

**Comment by ArtPoon** [comment]
I had to modify the Springer bibliography style file, but yes references are in order of appearance now

**Comment by mavino** [comment]
I guess you fixed already the last point ('not number acknowledgements section') as well. Is that so?

**Comment by ArtPoon** [comment]
I don't know why the Springer template does not have a separate section for endnotes.  Close for now.
